//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StrongHouseDBEntities : DbContext
    {
        public StrongHouseDBEntities()
            : base("name=StrongHouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TypeOfFlooring> TypeOfFloorings { get; set; }
        public virtual DbSet<TypeOfFlooringSample> TypeOfFlooringSamples { get; set; }
        public virtual DbSet<TypeOfCeiling> TypeOfCeilings { get; set; }
        public virtual DbSet<TypeOfCeilingSample> TypeOfCeilingSamples { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<TypeOfWalling> TypeOfWallings { get; set; }
        public virtual DbSet<TypeOfWallingSample> TypeOfWallingSamples { get; set; }
        public virtual DbSet<HouseDetail> HouseDetails { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<StoredPlan> StoredPlans { get; set; }
        public virtual DbSet<StoredFlooring> StoredFloorings { get; set; }
        public virtual DbSet<StoredWalling> StoredWallings { get; set; }
        public virtual DbSet<StoredCeiling> StoredCeilings { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
    }
}
