//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int ReplyId { get; set; }
        public Nullable<int> UserRefId { get; set; }
        public Nullable<int> CommentRefId { get; set; }
        public string Reply1 { get; set; }
        public Nullable<System.DateTime> ReplyDateTime { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
