//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredWalling
    {
        public int WallingId { get; set; }
        public Nullable<int> HouseRefId { get; set; }
        public Nullable<int> StoredTypeOfWallingRefId { get; set; }
        public Nullable<int> StoredTypeOfWallingSampleRefId { get; set; }
        public string WallingName { get; set; }
        public string WallingCategory { get; set; }
        public string WallingType { get; set; }
        public string TypeOfPartition { get; set; }
        public decimal WallingArea { get; set; }
        public string WallingSampleName { get; set; }
        public string WallingSampleCode { get; set; }
        public string WallingSampleBrand { get; set; }
        public Nullable<decimal> WallingSampleHight { get; set; }
        public Nullable<decimal> WallingSampleWidth { get; set; }
        public Nullable<decimal> WallingMililiters { get; set; }
        public Nullable<decimal> WallingSamplePrice { get; set; }
        public Nullable<decimal> WallingSampleMinAmount { get; set; }
        public Nullable<decimal> WallingSampleTotalCost { get; set; }
        public string SampleImagePath { get; set; }
    
        public virtual HouseDetail HouseDetail { get; set; }
    }
}
