//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredCeiling
    {
        public int CeilingId { get; set; }
        public int HouseRefId { get; set; }
        public Nullable<int> StoredTypeOfCeilingRefId { get; set; }
        public Nullable<int> StoredTypeOfCeilingSampleRefId { get; set; }
        public string CeilingName { get; set; }
        public string CeilingCategory { get; set; }
        public string CeilingType { get; set; }
        public string TypeOfPartition { get; set; }
        public decimal CeilingArea { get; set; }
        public string CeilingSampleName { get; set; }
        public string CeilingSampleCode { get; set; }
        public string CeilingSampleBrand { get; set; }
        public Nullable<decimal> CeilingSampleHight { get; set; }
        public Nullable<decimal> CeilingSampleWidth { get; set; }
        public Nullable<decimal> CeilingMililiters { get; set; }
        public Nullable<decimal> CeilingSamplePrice { get; set; }
        public Nullable<decimal> CeilingSampleMinAmount { get; set; }
        public Nullable<decimal> CeilingSampleTotalCost { get; set; }
        public string SampleImagePath { get; set; }
    
        public virtual HouseDetail HouseDetail { get; set; }
    }
}
