//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredPlan
    {
        public int StoredPlanId { get; set; }
        public Nullable<int> StoredPlanRefId { get; set; }
        public Nullable<int> HouseRefId { get; set; }
        public string TypeOfPlan { get; set; }
        public string PlanName { get; set; }
        public string Scale { get; set; }
        public string DrawnBy { get; set; }
        public string AdditionalInformation { get; set; }
        public string StoredPlanImagePath { get; set; }
    
        public virtual HouseDetail HouseDetail { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
