//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfCeilingSample
    {
        public int CeilingTypeSampleId { get; set; }
        public int TypeOfCeilingRefId { get; set; }
        public Nullable<int> ShopRefId { get; set; }
        public string CeilingTypeSampleCode { get; set; }
        public string CeilingTypeSampleName { get; set; }
        public int CeilingTypeSampleSizeHeight { get; set; }
        public int CeilingTypeSampleSizeWidth { get; set; }
        public Nullable<decimal> CeilingTypeSamplePrice { get; set; }
        public string CeilingTypeSampleImagePath { get; set; }
    
        public virtual TypeOfCeiling TypeOfCeiling { get; set; }
    }
}
