//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfFlooringSample
    {
        public int FlooringTypeSampleId { get; set; }
        public int TypeOfFlooringRefId { get; set; }
        public string FlooringTypeSampleCode { get; set; }
        public string FlooringTypeSampleName { get; set; }
        public int FlooringTypeSampleSizeHeight { get; set; }
        public int FlooringTypeSampleSizeWidth { get; set; }
        public Nullable<decimal> FlooringTypeSamplePrice { get; set; }
        public string FlooringTypeSampleImagePath { get; set; }
        public Nullable<int> ShopRefId { get; set; }
    
        public virtual TypeOfFlooring TypeOfFlooring { get; set; }
    }
}
