//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongHouseOwner.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfWalling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfWalling()
        {
            this.TypeOfWallingSamples = new HashSet<TypeOfWallingSample>();
        }
    
        public int WallingTypeId { get; set; }
        public string WallingTypeCategory { get; set; }
        public string WallingType { get; set; }
        public string WallingTypeDetails { get; set; }
        public Nullable<int> WallingTypeDeletion { get; set; }
        public string WallingTypeAdvantage { get; set; }
        public string WallingTypeDisadvantage { get; set; }
        public string WallingTypeBestUse { get; set; }
        public string WallingTypeReinstall { get; set; }
        public string WallingTypeImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfWallingSample> TypeOfWallingSamples { get; set; }
    }
}
